
# Run from siren
# >>> x_training.train_video_from_config(config_file)
logging_root:            /media/z/Malatesta/zXb/share/siren
experiment_name:        eclipse_512_sub
data_path:              ./data/eclipse_512
train_type:             video
batch_size:                   1
lr:                      0.0001
num_epochs:                  10
epochs_til_checkpoint:        1
steps_til_summary:          1
model_type:                sine
sample_frac:               null # 0.0038 if none, autocomute
checkpoint_path:           null
frame_range:               [0, 200] # if none autocompute [0,500]
verbose:                   1
# model parameters
siren:
  in_features:
    3
  out_features:
    3
  hidden_features:
    1024
  hidden_layers:
    3
  outermost_linear:
    true
  first_omega_0:
    30
  hidden_omega_0:
    30.